### PR TITLE
PDS Script cleanup

### PR DESCRIPTION
**Pull request by MarcHagen**
Added instance feedback from PDS
Added data polling, for feedback
Updated error handling for inputs

### CODE REVIEW

**Comment by willosof** [comment]
Tested?:)

**Review by willosof — COMMENTED** [review]
Indentation issues. Spaces instead of tabs some places

**Comment by MarcHagen** [comment]
As always, i'm runnning this currently at a conf center.
Altho i have a 902 PDS here, the 901/701 should have the same firmware and so same commands/responses.

**Comment by dnmeid** [comment]
Thanks for all the effort you put in that module and sorry for not responding for such a long time. Can you please check the identation again (we use tabs) and bring the PR to an auto-mergable level.

**Comment by MarcHagen** [comment]
> Thanks for all the effort you put in that module and sorry for not responding for such a long time. Can you please check the identation again (we use tabs) and bring the PR to an auto-mergable level.

@dnmeid Let me know what you guys think. It still works. Using it every week in the dev version

**Comment by MarcHagen** [comment]
@willosof @dnmeid Still love to see this updated.

**Pull request merged**
